config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :favorite_jokes, only: %i[index new create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "favorite_jokes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite_joke.rb
class FavoriteJoke < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorite_jokes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/favorite_jokes_controller.rb
class FavoriteJokesController < ApplicationController
  before_action :authenticate_user!

  # GET /favorite_jokes or /favorite_jokes.json
  def index
    @favorite_jokes = current_user.favorite_jokes.all.order(id: :desc)
  end

  # GET /favorite_jokes/new
  def new
    caller = CallNorris.new
    @joke = caller.get_joke
    @favorite_joke = FavoriteJoke.new
  end

  # POST /favorite_jokes or /favorite_jokes.json
  def create
    @favorite_joke = FavoriteJoke.new(favorite_joke_params)

    respond_to do |format|
      if @favorite_joke.save
        format.html { redirect_to favorite_jokes_url, notice: "Joke was succesfully saved" }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @favorite_joke.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def authenticate_user!
      if user_signed_in?
        super
      else
        redirect_to new_user_session_path
      end
    end

    # Only allow a list of trusted parameters through.
    def favorite_joke_params
      params.require(:favorite_joke).permit(:value, :icon_url, :joke_id, :url, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorite_jokes_helper.rb
module FavoriteJokesHelper
end

app/views/favorite_jokes/_favorite_joke.html.erb
<div id="<%= dom_id favorite_joke %>">
  <section class="h-100">
    <div class="container py-5 text-center">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-xl-10">
          <div class="card">
            <div class="card-body py-5">
              <div class="carousel-item active">
                <div class="row d-flex justify-content-center">
                  <div class="col-md-8 col-lg-9 col-xl-8">
                    <div class="d-flex">
                      <div class="flex-grow-1 ms-4 ps-3">
                        <figure>
                          <blockquote class="blockquote mb-4">
                            <p>
                              <i class="bi bi-quote"></i>
                              <span class="font-italic"><%= favorite_joke['value'] %></span>
                            </p>
                          </blockquote>
                        </figure>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/favorite_jokes/_form.html.erb
<div class="text-center">
<%= form_for @favorite_joke do |form| %>
    <%= form.hidden_field :value, value: @joke['value'], style: "display: block" %>
    <%= form.hidden_field :icon_url, value: @joke['icon_url'], style: "display: block" %>
    <%= form.hidden_field :joke_id, value: @joke['joke_id'], style: "display: block" %>
    <%= form.hidden_field :url, value: @joke['url'], style: "display: block" %>
    <%= form.hidden_field :user_id, value: current_user.id, style: "display: block" %>
    <%= form.submit "Save favorite joke", class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/favorite_jokes/_joke.html.erb
  <div id="new-joke" class="h-100">
    <div class="container py-5 text-center">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-xl-10">
          <div class="card">
            <div class="card-body py-5">
              <div class="carousel-item active">
                <div class="row d-flex justify-content-center">
                  <div class="col-md-8 col-lg-9 col-xl-8">
                    <div class="d-flex">
                      <div class="flex-grow-1 ms-4 ps-3">
                        <figure>
                          <blockquote class="blockquote mb-4">
                            <p>
                              <i class="bi bi-quote"></i>
                              <span class="font-italic"><%= @joke['value'] %></span>
                            </p>
                            <p>
                            <%= render 'form', favorite_joke: @joke %>
                            </p>
                          </blockquote>
                        </figure>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>

app/views/favorite_jokes/edit.html.erb
<h1>Editing favorite joke</h1>

<%= render "form", favorite_joke: @favorite_joke %>

<br>

<div>
  <%= link_to "Show this favorite joke", @favorite_joke %> |
  <%= link_to "Back to favorite jokes", favorite_jokes_path %>
</div>

app/views/favorite_jokes/index.html.erb
<div class="container text-center">
  <div class="row">
    <p style="color: green"><%= notice %></p>
    <div class="text-center"><%= image_tag "chuck.jpg", style: "max-width: 300px; max-height: 300px", class: "img-responsive" %></div>
    <br>
    <h1> Chuck's Jokes App</h1>
    <p>Here you can find curated Chuck Norris facts, and also save the ones you like most!<p>
  </div>
  <div class="row">
    <div class="col">
      <%= link_to "Get Joke", new_favorite_joke_path, class: 'btn btn-primary', data: { turbo_frame: 'joke' } %>
      <br><br>
      
      <h5 class="fw-bold">My Jokes</h5>

      <% turbo_stream_from :favorite_jokes %>

      <div id="joke"></div>
      
      <%= turbo_frame_tag "favorite_joke" do %>
        <p style="color: green"><%= notice %></p>
        <%= render @favorite_jokes %> 
      <% end %>
    </div>
  </div>
</div>

app/views/favorite_jokes/new.html.erb
<%= turbo_frame_tag "joke" do %>
  <%= render "joke", favorite_joke: @favorite_joke %>
<% end %>

app/views/favorite_jokes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @favorite_joke %>

<div>
  <%= link_to "Edit this favorite joke", edit_favorite_joke_path(@favorite_joke) %> |
  <%= link_to "Back to favorite jokes", favorite_jokes_path %>

  <%= button_to "Destroy this favorite joke", @favorite_joke, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <%= render 'shared/head' %>
  </head>

  <body class="d-flex flex-column h-100 gradient-custom">
    <main class="flex-shrink-0"> 
      <%= render 'shared/navbar' %>

      <div class="container mt-4 mx-auto">
        <%= turbo_frame_tag "joke" %>
        <%= turbo_frame_tag "favorite_joke" %>
        <%= yield %>
      </div>
    </main>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<%= stylesheet_link_tag "footer", "data-turbo-track": "reload" %>

<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="bootstrap" viewBox="0 0 118 94">
    <title>Bootstrap</title>
    <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
  </symbol>
  <symbol id="facebook" viewBox="0 0 16 16">
    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"></path>
  </symbol>
  <symbol id="instagram" viewBox="0 0 16 16">
      <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"></path>
  </symbol>
  <symbol id="twitter" viewBox="0 0 16 16">
    <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"></path>
  </symbol>
</svg>

<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <%= link_to image_tag('chuck.jpg', style: "max-width: 50px; max-height: 50px; border-radius: 50%; margin-right: 10px") %>
      </a>
      <span class="mb-3 mb-md-0 text-muted">© 2022 <%= link_to "francoasdev", "https://francozapata.tech/" %></span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-muted" href="https://twitter.com/francoasdev"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="https://www.instagram.com/francoasdev/"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
    </ul>
  </footer>
</div>

app/views/shared/_head.html.erb
<title>Chuck's Jokes App</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg" aria-label="Fifth navbar example">
  <div class="container-fluid">
      <%= link_to image_tag('chuck.jpg', style: "max-width: 50px; max-height: 50px; border-radius: 50%"), root_path %>
      <% if user_signed_in? %>
        <%= link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", bs_toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
          <%= image_tag 'chuck.jpg', height: 30, width: 30, class: "rounded", style:"border-radius: 50%" %>
        <% end %>
        <div id="nav-account-dropdown" class="dropdown-menu dropdown-menu-end" aria-labelledby="navbar-dropdown">
          <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      <% else %>
        <div class="btn-toolbar">
          <div class="ms-1"><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %></div>
          <div class="ms-1"><%= link_to "Login", new_user_session_path, class: "btn btn-primary" %></div>
        </div>
      <% end %>
  </div>
</nav>